Impression.create!([
  {impressionable_type: "Submission", impressionable_id: 0, user_id: 1, controller_name: "submissions", action_name: "show", view_name: nil, request_hash: "06e4a9697c1542bc441f935d19f85caaf7d67d64ca5f769fac7a8a4ce8009af9", ip_address: "::1", session_hash: "9deaa1dde92772f44f9fc8a9100cf824", message: nil, referrer: "http://localhost:3000/submissions/1/edit?type=petition"},
  {impressionable_type: "Submission", impressionable_id: 1, user_id: 1, controller_name: "submissions", action_name: "show", view_name: nil, request_hash: "06e4a9697c1542bc441f935d19f85caaf7d67d64ca5f769fac7a8a4ce8009af9", ip_address: "::1", session_hash: "9deaa1dde92772f44f9fc8a9100cf824", message: nil, referrer: "http://localhost:3000/submissions/1/edit?type=petition"},
  {impressionable_type: "Submission", impressionable_id: 0, user_id: 1, controller_name: "submissions", action_name: "show", view_name: nil, request_hash: "06e4a9697c1542bc441f935d19f85caaf7d67d64ca5f769fac7a8a4ce8009af9", ip_address: "::1", session_hash: "9deaa1dde92772f44f9fc8a9100cf824", message: nil, referrer: "http://localhost:3000/submissions/1/edit?type=petition"},
  {impressionable_type: "Submission", impressionable_id: 1, user_id: 1, controller_name: "submissions", action_name: "show", view_name: nil, request_hash: "06e4a9697c1542bc441f935d19f85caaf7d67d64ca5f769fac7a8a4ce8009af9", ip_address: "::1", session_hash: "9deaa1dde92772f44f9fc8a9100cf824", message: nil, referrer: "http://localhost:3000/submissions/1/edit?type=petition"}
])
# User.create!([
#   {email: "sam@smallchangegiving.net", encrypted_password: "$2a$10$LaV2xXkOpiq2plFnKCVOvuEQE7WGvnIht6y.DgqcSz7mQ6XkeRdly", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 9, current_sign_in_at: "2016-04-22 01:06:12", last_sign_in_at: "2016-04-21 23:45:30", current_sign_in_ip: "::1", last_sign_in_ip: "::1", admin: true, actions_taken: 0, first_name: "Sam", last_name: "Henderson", mobile: "+61432211241", terms_of_service: true, charity_id: nil, confirmation_token: "ao3PWzEexqYHD6LwNBQx", confirmed_at: nil, confirmation_sent_at: "2016-04-20 09:48:33", unconfirmed_email: nil},
#   {email: "hendersonsam456@gmail.com", encrypted_password: "$2a$10$0NzoMKdLRQsCJmT7BdO83Ou2tY9k2lXunCqO.vY.XYIhscxgiMYgu", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 9, current_sign_in_at: "2016-04-22 01:06:21", last_sign_in_at: "2016-04-21 23:24:54", current_sign_in_ip: "::1", last_sign_in_ip: "::1", admin: false, actions_taken: 0, first_name: "Sam", last_name: "Henderson", mobile: "+61432211241", terms_of_service: true, charity_id: 2, confirmation_token: "2jpJ_92jjPfGfJ6HTyYQ", confirmed_at: "2016-04-20 10:07:12", confirmation_sent_at: "2016-04-20 10:06:01", unconfirmed_email: nil}
# ])
Charity.create!([
  {name: "Greenpeace", bsb: "1234563", account_number: "123456", contact_name: "Peter Smith", contact_email: "peter@gmail.com", url: "http://www.greenpeace.org/australia/en/", logo: "http://res.cloudinary.com/small-change/image/upload/v1456287080/greenpeace_logo-compressor_jm3ehh.png", blurb: "Greenpeace states its goal is to \"ensure the ability of the Earth to nurture life in all its diversity and focuses its campaigning on worldwide issues such as climate change, deforestation, overfishing, commercial whaling, genetic engineering, and anti-nuclear issues. It uses direct action, lobbying, and research to achieve its goals."},
  {name: "GetUp!", bsb: "12345763", account_number: "1234756", contact_name: "Peter Bryan", contact_email: "bryan@gmail.com", url: "https://www.getup.org.au/", logo: "https://www.getup.org.au/assets/public/getup_logo-80e6b538167941e6c28fa3b2ef35b84a.png", blurb: "GetUp is one of Australia's largest campaigning communities, with a membership of over 1,000,000 people. We're an independent, grassroots, community advocacy organisation that seeks to build a more progressive Australia and hold politicians to account. Whether it is campaigning on climate action, economic fairness, environmental sustainability or issues of social justice, GetUp members combine to demand better from our government, big business and media."}
])
CharityCategory.create!([
  {charity_id: 1, category_name: "Whaling", description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. "},
  {charity_id: 1, category_name: "Environment", description: "The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here',"},
  {charity_id: 2, category_name: "Great Barrier Reef Protection", description: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour"},
  {charity_id: 2, category_name: "Gay Marriage", description: "The description for the charity category would go here and would be about this long presumably."}
])
Submission.create!([
  {url: "//www.youtube.com/embed/bek1y2uiQGA", title: "Avicii vs Nicky Romero - I Could Be The One (Nicktim)", favicon: "https://upload.wikimedia.org/wikipedia/commons/0/06/YouTube_logo_2013.svg", description: "Buy it on Itunes over here: http://umusic.ly/hep5mn Amazon: http://umusic.ly/efe0jy Official video for Avicii vs Nicky Romero - I Could Be The One (Nicktim)....", image: "https://i.ytimg.com/vi/bek1y2uiQGA/hqdefault.jpg", charity: nil, petition_link: "https://www.youtube.com/watch?v=bek1y2uiQGA", submission_type: "petition", link_clicks: 0, slug: "avicii-vs-nicky-romero-i-could-be-the-one-nicktim", user_id: 1, charity_category_id: 3, youtube: true},
  {url: "http://www.smh.com.au/federal-politics/political-news/apec-malcolm-turnbull-and-barack-obama-hit-it-off-resist-pressure-for-troops-in-syria-20151117-gl18hw.html", title: "Turnbull and Obama hit it off, resist pressure for troops in Syria", favicon: "http://www.smh.com.au/favicon.ico", description: "The Turnbull government is predicting an escalation of the military assault on Islamic State&nbsp;in Syria as a result of the emergent partnership between the US and Russia.", image: "http://www.smh.com.au/content/dam/images/g/l/1/c/j/2/image.related.articleLeadwide.620x349.gl18hw.png/1448059113521.jpg", charity: nil, petition_link: nil, submission_type: nil, link_clicks: 0, slug: "turnbull-and-obama-hit-it-off-resist-pressure-for-troops-in-syria", user_id: 2, charity_category_id: nil, youtube: nil}
])
